### ISSUE TITLE
Fails with no null task

### ISSUE THREAD

**Issue by ghost** [fizista/micropython-scron#4]
In the readme, you mention the need to add a null task

```
# Depending on the device, you need to add a task that
# will be started at intervals shorter than the longest
# time the timer can count.
simple_cron.add('null', lambda *a, **k: None, seconds=0, minutes=range(0,59,5), removable=False)


```
I think it's better to do that mandatory, or better, automatic.

I spent three days chasing a bug related to this ...

**Comment by fizista** [comment]
If this library was only for esp8266 then it would make sense. You don't always need that entry. If you have a permanent task that is called up as often as the maximum timer time, then you don't need this entry either.

The problem is actually documentation where this problem is not visible enough.

**Comment by fizista** [comment]
Thank you for bringing the problem to my attention.

**Comment by ghost** [comment]
On 5/5/20 7:59 AM, Wojciech Banaś wrote:
>
> If this library was only for esp8266 then it would make sense. You 
> don't always need that entry. If you have a permanent task that is 
> called up as often as the maximum timer time, then you don't need this 
> entry either.
>
> The problem is actually documentation where this problem is not 
> visible enough.
>
I was running my code on a ESP32.

Very convenient library. Worth the three day bug-hunting.

Candid Moe
