### ISSUE TITLE
run_times make recursion error when program uses threads

### ISSUE THREAD

**Issue by ghost** [fizista/micropython-scron#5]
[Tested on a ESP32]

When using decorator `run_times` and the program also run threads, `simple_cron` may fail with 'recursion error':

![image](https://user-images.githubusercontent.com/46725121/81288768-4b57d280-9033-11ea-8ac7-a15fb6f56f04.png)

This test program fails most of the times. If you delete the `run_time` decorator (or comment out the `counter` thread), it runs OK:

    import _thread
    import time
    from scron.week import simple_cron
    from scron.decorators import run_times

    def nowplus(seconds):
        '''Compute now plus seconds
        '''
        future = time.time() + seconds
        year, month, mday, hour, minute, second, weekday, yearday = time.localtime(future)
        return {
            'weekdays': weekday,
            'hours': hour,
            'minutes': minute,
            'seconds': second
            }

    def counter():
        '''A simple thread'''
        counter = 0
        while True:
            print(counter)
            counter += 1
            time.sleep(15)
            
                        
    print("Starting ...")
    _thread.start_new_thread(counter, ())
    simple_cron.add("null task", lambda *a, **k: None, seconds=0, minutes=range(0,59,5), removable=False)
    simple_cron.add("Cosa 1", run_times(1)(lambda a, b, c, d: print("Hello, World")), **nowplus(10))
    simple_cron.run()

    print("Waiting for 'Hello, World'")
    time.sleep(30)
    print("End")

`

**Comment by fizista** [comment]
What version of MicroPython do you have installed? What model of ESP32 board do you have? How much RAM do you have on it?

On ESP32 I have almost never had this problem. Especially in such a simple case.

You may have read this thread:
https://forum.micropython.org/viewtopic.php?t=2034

**Comment by fizista** [comment]
Do you use MicroPython(mpy) binary files for the SimpleCron library?
https://docs.micropython.org/en/latest/reference/mpyfiles.html

**Comment by ghost** [comment]
On 5/7/20 10:02 AM, Wojciech Banaś wrote:
>
> Do you use MicroPython(mpy) binary files for the SimpleCron library?
>
No. I ran this commands on the ESP32:

     import upip

     upip.install("micropython-scron")


Andrés

**Comment by fizista** [comment]
See this library:

https://github.com/fizista/micropython-mcron

I just uploaded it. It's similar in operation to SimpleCRON. 

It's much smaller than SimpleCRON, but it works. I haven't written good documentation yet, but I think you can do it without it.

In the SimpleCRON library I got some experience in writing applications under MicroPython. Therefore, MicroCRON should be better than the current library.

**Comment by ghost** [comment]
*Configuration*


*Micropython*

MicroPython v1.12-388-g388d419ba on 2020-04-22; ESP32 module with ESP32

*Board*

ESP32-WROOM-32, on a chinese DevKitC type:

*Memory*


 >>>You may have read this thread:
 >>>https://forum.micropython.org/viewtopic.php?t=2034 
<https://forum.micropython.org/viewtopic.php?t=2034>

I read it now. However, the test code provided doesn't use recursion.


Candid

**Comment by fizista** [comment]
This code works as you'd expect:
```
import time
from scron.week import simple_cron
from scron.decorators import run_times

def nowplus(seconds):
    '''Compute now plus seconds
    '''
    future = time.time() + seconds
    year, month, mday, hour, minute, second, weekday, yearday = time.localtime(future)
    return {
        'weekdays': weekday,
        'hours': hour,
        'minutes': minute,
        'seconds': second
        }


def counter():
    '''A simple thread'''
    counter = 0
    while True:
        print(counter)
        counter += 1
        time.sleep(15)
        
                    
print("Starting ...")
simple_cron.run()
simple_cron.add("null task", lambda *a, **k: None, seconds=0, minutes=range(0,59,1), removable=False)
simple_cron.add("Cosa 1", run_times(1)(lambda a, b, c, d: print("Hello, World")), **nowplus(10))


print("Waiting for 'Hello, World'")
for i in range(30):
    print(i)
    time.sleep(1)
print("End")
```

Looks like it's better not to use threads.

**Comment by ghost** [comment]
I was using threads before, but I think that a cron/scheduler solution is better. Pity it didn't work,
Anyway, here his the threads version of the code:

    import _thread
    import time

    def hello_world(seconds):
        time.sleep(seconds)
        print("Hello, World");


    def counter():
        '''A simple thread'''
        counter = 0
        while True:
            print(counter)
            counter += 1
            time.sleep(15)
            
                        
    print("Starting ...")
    _thread.start_new_thread(counter, ())
    _thread.start_new_thread(hello_world, (10,))

    print("Waiting for 'Hello, World'")
    time.sleep(30)
    print("End")
